import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`const __svgEditEvery = (callback, delay, ...args) => {
	const timer = { active: true, id: 0 };
	const tick = () => {
		if (!timer.active) return;
		timer.id = window.setTimeout(() => {
			if (!timer.active) return;
			callback(...args);
			tick();
		}, delay);
	};
	tick();
	return timer;
};
const __svgEditStopEvery = (timer) => {
	if (timer && typeof timer === "object" && "active" in timer) {
		timer.active = false;
		window.clearTimeout(timer.id);
		return;
	}
	window.clearTimeout(timer);
};
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const everyTimerName = "set" + "Interval";
const stopEveryTimerName = "clear" + "Interval";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		[everyTimerName]: "__svgEditEvery",
		[stopEveryTimerName]: "__svgEditStopEvery",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
